### ISSUE TITLE
Error about the evaluation process

### ISSUE THREAD

**Issue by jennifer1995** [X3N4/neural_citation#3] opened 2021-03-08 02:39 UTC
Thank you for sharing these codes! I am very grateful to reproduce the results of the experiment.
There are some errors when I try to excute the evaluation.
I have transferred the `NCN_evaluation.ipynb` into .py file, and use `NCN_9_4_4_128_filters.pt`, but it comes to the errors below:

```
Traceback (most recent call last):
  File "NCN_evaluation.py", line 23, in <module>
    evaluator = Evaluator([4,4,5,6,7], [1,2], 128, 128, 2, path_to_weights, data, evaluate=True, show_attention=False)
  File "/home2/yy/dmcproject/neural_citation/ncn/evaluation.py", line 64, in __init__
    self.model.load_state_dict(torch.load(path_to_weights, map_location=DEVICE))
  File "/home2/yy/port22/anaconda2/envs/KD/lib/python3.7/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NeuralCitationNetwork:
	size mismatch for encoder.context_embedding.weight: copying a param with shape torch.Size([20002, 128]) from checkpoint, the shape in current model is torch.Size([2, 128]).
	size mismatch for decoder.embedding.weight: copying a param with shape torch.Size([20004, 128]) from checkpoint, the shape in current model is torch.Size([4, 128]).
	size mismatch for decoder.out.weight: copying a param with shape torch.Size([20004, 384]) from checkpoint, the shape in current model is torch.Size([4, 384]).
	size mismatch for decoder.out.bias: copying a param with shape torch.Size([20004]) from checkpoint, the shape in current model is torch.Size([4]).
```

Can you help me ? Thank you very much.

**Comment by timoklein** [comment] 2021-03-12 17:18
Hey Jennifer,
I have tried to reproduce your error but I have rerun the evaluation notebook and it works for me. 
![ncn_works](https://user-images.githubusercontent.com/36668911/110974445-d219c200-835e-11eb-98c7-a80ecfb98f8c.png)
Do you want to share more of your code so I can take a look?
What vocab size have you put in this call?
```python
data = get_datasets(path_to_data, 20000, 20000, 20000)
```

**Comment by timoklein** [comment] 2021-03-26 06:04
Since you haven't replied in two weeks I'm going to close this. Feel free to reopen the issue if anything is unclear.

**Closed as completed by timoklein** 2021-03-26 06:04 UTC
